This should add all the audio back except for the lines causing the error from before
bridge-core/editor pull request #27
Opened 2021-05-24 18:39 UTC by outercloudstudio

## Description
It added back the removed lines of code except for the one in base window.

## Motivation and Context
This fixed the weird circle dependencies errors being caused.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have tested my changes and confirmed that they are working

2021-05-25 09:01 UTC, solvedDev requested changes

2021-05-25 09:01 UTC, solvedDev commented on src/components/Windows/LoadingWindow/LoadingWindow.ts
> +		//new Audio('/audio/click5.ogg').play()
Can we remove the comments in this file and replace them with `// TODO: Add sounds`?

2021-05-25 09:01 UTC, solvedDev commented on src/components/Windows/UnsavedFile/UnsavedFile.ts
> +		//new Audio('/audio/click5.ogg').play()
Same here.

2021-05-25 13:05 UTC, outercloudstudio commented
This should fix it.

2021-05-26 08:46 UTC, solvedDev approved these changes
LGTM, thanks 👏

2021-05-26 08:46 UTC, merged