feat: tree editor validation
bridge-core/editor pull request #825
Opened 2022-12-29 12:55 UTC by solvedDev

## Description
This PR implements file validation for bridge. v2's tree editor based on JSON schemas.

## Motivation
closes #101 

## Additional Context
This PR additionally makes the following changes to improve the tree editor:
- Always select first auto-completion item for quicker typing
- Disable spellchecking and browser auto-complete within tree editor inputs
- Ensure auto-complete menu always opens below the inputs
- Properly support dynamic auto-completions for the current file within tree editor (e.g. events from the current file)

## Todos:
- [ ] Figure out why file validation only kicks in after a first edit
- [ ] Hover text for error within child indicator
- [ ] Display error within context menu?

2023-01-05 19:39 UTC, Joelant05 requested changes
When the node is expanded by clicking the warning icon, the tooltip as seen in the video below persists even when scrolling and closing the node 

I did also experience an error but was only able to produce it once, I will add another review if I can find the issue again

https://user-images.githubusercontent.com/64587014/210865244-69bfccb7-1d24-4c55-9c5f-c6802ded4fae.mp4

2023-01-05 19:43 UTC, solvedDev commented
Good catch, will fix tomorrow 👍

2023-01-07 15:00 UTC, Joelant05 approved these changes

2023-01-07 15:01 UTC, merged

2023-03-16 08:38 UTC, Mosteuh commented
Hi i can't find were to activate tree editor were do we find it plz its been 1hour nothing can be find on internet to "how to activate tree editor in bridge v2" beside activating it from installation